base_dir: '/media/user/euclid-cutouts'
name: 'v1'
release_name: 'Q1_R1'
sas_environment: 'PDR'  
bands: ['VIS', 'NIR_Y']

credentials_file: '/media/user/cred.txt' 

num_tiles: 0  # all tiles
refresh_catalogs: False

download_method: 'datalabs_path'  # or sas
delete_tiles: False
debug: False
run_async: True  # necessary for GZ selection_function
max_retries: 5
seed: 1

# selection_cuts: space_warps
selection_cuts: galaxy_zoo_generous
field_of_view: galaxy_zoo  # or number in arcseconds
# field_of_view: 15

jpg_outputs: [
  'gz_arcsinh_vis_only', 'gz_arcsinh_vis_y', 'gz_arcsinh_vis_lsb', 'sw_mtf_vis_y']   # typical GZ images + vis y MTF from space warps
add_bkg: true
fits_outputs: false
overwrite_jpg: true
overwrite_fits: false
jpg_quality: 98
use_fits_origin_for_jpg: true

# ignore these
download_dir: !
tile_dir: !
catalog_dir: ''
cutout_dir: !
jpg_dir: !
fits_dir: !
sanity_dir: !
log_file: !
