release_name: F-006  # the latest Wide survey data on OTF
num_tiles: 4
refresh_catalogs: True  # always overwrite/redownload catalogs
seed: 1
delete_tiles: False  # set True to clean up tiles as we go
debug: True  # currently does nothing
run_async: False  # use async sql queries in SAS. Useful for downloading more than 2k galaxies per tile.
max_retries: 1  # retry failed tile downloads
selection_cuts: galaxy_zoo  # or lens_candidates
base_dir: '/media/home/my_workspace/tmp'  # to tinker without sharing the results
name: 'example_run'

# these are set by the code
download_dir: !
tile_dir: !
catalog_dir: !
cutout_dir: !
jpg_dir: !
fits_dir: !
sanity_dir: !
log_file: !

