release_name: F-006
ra_upper_limit: 100
dec_upper_limit: -20
num_tiles: 2
seed: 1
debug: True

base_dir: '/home/walml/dummy_euclid_volume/data'
download_dir: 'pipeline/runs/debug'
tile_dir: !
catalog_dir: !
cutout_dir: !
jpg_dir: !

# tiling_strategy_loc: 'tiling_plan/field_all_sky_overview.fits'