base_dir: '/media/home/team_workspaces/Euclid-Consortium/data/strong_lensing/external_targets_pipeline'
name: 'mer_catalog_debug'
release_name: F-006

bands: ['VIS', 'NIR_Y', 'NIR_J', 'NIR_H']

num_tiles: 2  # all tiles
refresh_catalogs: False  # WARNING
delete_tiles: False
debug: False
run_async: True  # necessary for strong lens selection func
max_retries: 1
seed: 1

selection_cuts: space_warps
# field_of_view: galaxy_zoo  # or number in arcseconds
field_of_view: 20  # or number in arcseconds

# jpg_outputs: ['composite', 'vis_only', 'vis_lsb']
jpg_outputs: ['vis_only_sw', 'vis_y_sw', 'vis_low_y_sw', 'vis_j_sw']
fits_outputs: True
overwrite_jpg: True
overwrite_fits: True

download_dir: !
tile_dir: !
catalog_dir: !
cutout_dir: !
jpg_dir: !
fits_dir: !
sanity_dir: !
log_file: !
