release_name: F-006
ra_upper_limit: 100
dec_upper_limit: -20
num_tiles: 200
seed: 1
debug: False

base_dir: '/media/home/team_workspaces/Galaxy-Zoo-Euclid/data'
download_dir: 'pipeline/runs/v3_challenge_midaug'
tile_dir: !
catalog_dir: !
cutout_dir: !
jpg_dir: !
sanity_dir: !
log_file: !

# tiling_strategy_loc: 'tiling_plan/field_all_sky_overview.fits'