release_name: F-006
ra_upper_limit: 100
dec_upper_limit: -20
num_tiles: 2
refresh_catalogs: True
seed: 1
debug: True

base_dir: '/media/home/team_workspaces/Galaxy-Zoo-Euclid/data/pipeline_runs'
name: 'remote_debug'
download_dir: !
tile_dir: !
catalog_dir: !
cutout_dir: !
jpg_dir: !
sanity_dir: !
log_file: !

# tiling_strategy_loc: 'tiling_plan/field_all_sky_overview.fits'