# for the master list of external sl-related targets
base_dir: '/media/home/team_workspaces/Euclid-Consortium/data/strong_lensing/external_targets_pipeline'
name: 'q1_discovery_engine_data_release_v1_inc_ext_data_repeated'

# external_targets_loc: /media/home/my_workspace/repos/bulk-euclid-cutouts/bulk_euclid/external_targets/judges_latest_ml_only_catalog_external_targets.csv
# external_targets_loc: /media/home/my_workspace/repos/bulk-euclid-cutouts/bulk_euclid/external_targets/judges_latest_catalog_external_targets.csv
# external_targets_loc: /media/home/my_workspace/repos/bulk-euclid-cutouts/bulk_euclid/external_targets/q1_discovery_engine_targets_for_bulk_cutout_download.csv

# _review version includes Valerio's recentering
external_targets_loc: /media/home/my_workspace/repos/bulk-euclid-cutouts/bulk_euclid/external_targets/q1_discovery_engine_targets_for_bulk_cutout_download_review.csv

release_name: Q1_R1  # Q1 data only, will be missing for non-Q1 lenses (just use those already uploaded?)
# bands: ['VIS', 'NIR_Y', 'NIR_J', 'NIR_H']  # all bands

# CFIS is CFHT megacam, WISHES is HSC
# bands: ['CFIS_U', 'WISHES_G', 'CFIS_R', 'VIS', 'WISHES_Z', 'NIR_Y', 'NIR_J', 'NIR_H']  # all bands inc. EXT
bands: ['VIS', 'NIR_Y', 'NIR_J', 'NIR_H'] # many Q1 tiles don't have EXT except DECAM 

data_products: ['BGSUB', 'BGMOD', 'RMS', 'PSF']
add_bkg: False

jpg_outputs: ['sw_mtf_vis_only', 'sw_mtf_vis_y', 'sw_mtf_vis_j', 'sw_mtf_vis_y_j', 'sw_arcsinh_vis_only', 'sw_arcsinh_vis_y', 'sw_arcsinh_vis_j', 'sw_arcsinh_vis_y_j']
jpg_quality: 98
use_fits_origin_for_jpg: true

fits_outputs: true

overwrite_jpg: false
overwrite_fits: false

healpix_loc: '/media/user/repos/bulk-euclid-cutouts/data/tile_index_map.v1.2.fits.gz'
