# for ad hoc download of GZCD and GZ Euclid targets
base_dir: '/media/home/team_workspaces/Euclid-Consortium/data/strong_lensing/external_targets_pipeline'
name: 'wide_partial_gzcd'
release_name: null  # allow tiles from any release. Read as None in Python.
bands: ['VIS', 'NIR_Y']

# external_targets_loc: /media/home/my_workspace/repos/bulk-euclid-cutouts/bulk_euclid/external_targets/top_lenses_gz_euclid.csv
# external_targets_loc: /media/home/my_workspace/repos/bulk-euclid-cutouts/bulk_euclid/external_targets/top_lenses_gz_euclid_round_2.csv
external_targets_loc: /media/home/my_workspace/repos/bulk-euclid-cutouts/bulk_euclid/external_targets/top_lenses_gzcd_target_list.csv

auxillary_products: ['MERPSF', 'MERRMS']
release_priority: ['CALBLOCK_PV-005_R2', 'CALBLOCK_PV-005_R3', 'F-003_240321', 'F-003_240612' , 'F-006']
overwrite_fits: false
delete_tiles: true
fits_outputs: true
jpg_outputs: ['vis_only', 'vis_y']  # only the two safe bands, for now, pending reprocessing

# ignore these

download_dir: !
tile_dir: !
cutout_dir: !
fits_dir: !
jpg_dir: !
sanity_dir: !