base_dir: '/media/home/team_workspaces/Euclid-Consortium/data/strong_lensing/external_targets_pipeline'
name: 'wide_partial'
release_name: null  # allow tiles from any release. Read as None in Python.
# bands: ['VIS', 'NIR_Y', 'NIR_J', 'NIR_H']
bands: ['VIS', 'NIR_Y']

auxillary_products: ['MERPSF', 'MERRMS']
release_priority: ['CALBLOCK_PV-005_R2', 'CALBLOCK_PV-005_R3', 'F-003_240321', 'F-003_240612' , 'F-006']
overwrite_fits: false
delete_tiles: true
fits_outputs: true
jpg_outputs: ['vis_only', 'vis_y']

# ignore these

download_dir: !
tile_dir: !
cutout_dir: !
fits_dir: !
jpg_dir: !
sanity_dir: !